org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
neo_version_range=[21.1.234,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
moddev_version=2.0.142
fabric_loom_version=1.17.17
fabric_loader_version=0.19.3
fabric_api_version=0.116.15+1.21.1
fabric_language_kotlin_version=1.13.12+kotlin.2.4.0
modmenu_version=11.0.4
kotlin_version=2.4.0
kotlin_for_forge_version=5.12.0
kotest_version=6.2.3
fastutil_version=8.5.12
gson_version=2.10.1
paper_api_version=1.21.1-R0.1-SNAPSHOT
loader_version_range=[5.12,6)

mod_id=emotify
mod_name=Emotify
mod_license=MIT
mod_version=0.5.1
mod_group_id=me.whish
mod_authors=TheWhish
mod_description=Share lightweight animated emotions above players.
