org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
neo_version_range=[21.1.234,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
moddev_version=2.0.144
fabric_loom_version=1.17.17
fabric_loader_version=0.19.3
fabric_api_version=0.116.15+1.21.1
fabric_language_kotlin_version=1.13.12+kotlin.2.4.0
modmenu_version=11.0.4
minecraft_version_1_21_8=1.21.8
minecraft_version_range_1_21_8=[1.21.8]
neo_version_1_21_8=21.8.54
neo_version_range_1_21_8=[21.8.54,)
fabric_api_version_1_21_8=0.129.0+1.21.8
modmenu_version_1_21_8=15.0.2
gson_runtime_version_1_21_8=2.11.0
fastutil_runtime_version_1_21_8=8.5.15
minecraft_version_1_21_11=1.21.11
minecraft_version_range_1_21_11=[1.21.11]
neo_version_1_21_11=21.11.45
neo_version_range_1_21_11=[21.11.45,)
kotlin_for_forge_version_1_21_11=6.3.0
kotlin_for_forge_version_range_1_21_11=[6.3,7)
fabric_api_version_1_21_11=0.141.6+1.21.11
modmenu_version_1_21_11=17.0.0
gson_runtime_version_1_21_11=2.13.2
fastutil_runtime_version_1_21_11=8.5.18
minecraft_version_26_2=26.2
minecraft_version_range_26_2=[26.2]
neo_version_26_2=26.2.0.59
neo_version_range_26_2=[26.2.0.59,)
kotlin_for_forge_version_26_2=6.3.0
kotlin_for_forge_version_range_26_2=[6.3,7)
fabric_api_version_26_2=0.157.0+26.2
modmenu_version_26_2=20.0.1
kotlin_version=2.4.0
kotlin_for_forge_version=5.12.0
kotest_version=6.2.3
fastutil_version=8.5.12
gson_version=2.10.1
paper_api_version=1.21.1-R0.1-SNAPSHOT
paper_1_21_8_build=60
paper_1_21_8_sha256=8de7c52c3b02403503d16fac58003f1efef7dd7a0256786843927fa92ee57f1e
paper_1_21_11_build=132
paper_1_21_11_sha256=5ffef465eeeb5f2a3c23a24419d97c51afd7dbb4923ff42df9a3f58bba1ccfba
paper_26_2_build=112
paper_26_2_sha256=bd3a58cf96874e5ea6643f5f6fe9b4f5bf9e34b795fa078c2f0ee8b98b2f907e
folia_26_2_build=4
folia_26_2_sha256=19c81c308ba4de4b9fc0a61860c86281836d26ac046f696ea241766eea4b2468
loader_version_range=[5.12,6)

mod_id=emotify
mod_name=Emotify
mod_license=MIT
mod_version=0.8.0-beta.1
mod_group_id=me.whish
mod_authors=TheWhish
mod_description=Share lightweight animated emotions above players.
