package me.whish.emotify.domain

const val MAX_SELECTION_RETRY_AFTER_MILLIS = 10_000
const val SELECTION_REJECTION_BURST_CAPACITY = 2
const val SELECTION_REJECTION_REFILL_TOKENS_PER_SECOND = 1

enum class SelectionRejectionReason {
    COOLDOWN,
    SERVER_DISABLED,
    EMOTION_DISABLED,
    PLAYER_STATE,
    SERVER_BUSY,
}
