package me.whish.emotify.client.state

enum class ClientSelectionSendResult {
    SENT,
    NOT_CONNECTED,
    HANDSHAKE_UNAVAILABLE,
    EMOTION_UNAVAILABLE,
    CUSTOM_EMOJIS_UNSUPPORTED,
    CUSTOM_EMOJIS_DISABLED,
    CUSTOM_EMOJI_TOO_LARGE,
    CUSTOM_EMOJI_MISSING,
    PLAYER_STATE,
    CHANNEL_UNAVAILABLE,
    REQUEST_PENDING,
    REQUEST_THROTTLED,
    EMOTION_ACTIVE,
}
